In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [4]:
greeting('rwgnwriutgnwirun')

'Hello rwgnwriutgnwirun!'

In [5]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [6]:
basic_stats([1,2,3,4,5,6])

(1, 6, 3.5)

In [7]:
my_short_function = lambda name: f"Hello {name}!"

In [8]:
my_short_function(name="Super Man")

'Hello Super Man!'

In [1]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers,key=lambda x:x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [21]:
def greeting1(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [22]:
greeting1()

'Hello no one!'

In [16]:
?print

In [17]:
print("uvrisnrisu","Egrtgrg","334t34",sep="aaaaAAAAAAH",end="poopnuggets")

uvrisnrisuaaaaAAAAAAHEgrtgrgaaaaAAAAAAH334t34poopnuggets

In [28]:
def greeting2(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

In [30]:
greeting2(876)

'Hello 876!'

## Exercise 1
The function returns f'Hello {name}!' when name $\neq$ 'Batman'

In [14]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting('namvfdfsdfsfvdfa')

'Hello namvfdfsdfsfvdfa!'

In [95]:
x1=np.array([36, 34, 44, 76, 27])
y1=np.array([64, 66, 56, 24, 73])

In [10]:
#Exercise 2
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply (x,y):
    return x*y
def divide(x,y):
    if y==0:
        return 'noooooooooooooo'
        exit()
    return x/y
divide(2,0)

'noooooooooooooo'

In [97]:
add(x1,y1)

array([100, 100, 100, 100, 100])

In [98]:
subtract(x1,y1)

array([-28, -32, -12,  52, -46])

In [99]:
multiply(x1,y1)

array([2304, 2244, 2464, 1824, 1971])

In [100]:
divide(x1,y1)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [105]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [129]:
#Exercise 3
def max_info(numbers):
    return "max=", np.max(numbers), " index=", np.argmax(numbers)


In [130]:
max_info(numbers)

('max=', 77, ' index=', 7)