In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [34]:
print(np_real_names[0],np_super_names[0])

Natasha Romanoff Black Widow


In [10]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
#2d list

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [13]:
len(py_list_2d)

10

In [14]:
len(np_array_2d)

10

In [15]:
np_array_2d.shape

(10, 2)

In [16]:
py_list_2d.shape

AttributeError: 'list' object has no attribute 'shape'

In [17]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [18]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [19]:
np_array+10

array([11, 12, 13, 14, 15])

In [20]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [23]:
py_list_1+py_list_2
py_list_1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [24]:
np_array_1+np_array_2
np_array_1*2

array([ 2,  4,  6,  8, 10])

In [25]:
py_list = [ 2, 3, 4,5,6]
np_array = np.array(py_list)         

In [26]:
py_list>1

TypeError: '>' not supported between instances of 'list' and 'int'

In [27]:
np_array==3

array([False,  True, False, False, False])

In [28]:
np_array>3

array([False, False,  True,  True,  True])

In [30]:
sum(py_list)

20

In [31]:
sum(np_array)

20

In [32]:
np_array.mean()

4.0

In [33]:
#an operation on a list works on the whole list. In contrast, an operation on an array works on the individual elements of the array.

# Exercise 1
1. Two similarities between lists and arrays.

Both lists and arrays contain an ordered sequence of multiple elements.

If the list and array contain float numbers, the sum of all numbers can be found with the function sum(array/list).

2. Two differences between lists and arrays.

A list can contain different types of elements, while arrays can only have the same type of elements.

Functions on lists deal with all the elements at once, while with arrays, each element is dealt with seperately.

3. What is a dictionary?

A dictionary relates pairs of elements with each other.

In [37]:
#Exercise 2
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[::2])   # Prints 'i9'

['a1', 'c3', 'e5', 'g7', 'i9']


In [45]:
#Exercise 3
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper() 
superhero_info['Tony Stark']=superhero_info['Tony Stark'].upper()
superhero_info['Stephen Strange']=superhero_info['Stephen Strange'].upper()
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


In [72]:
#Exercise 4
np.numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
string_np_numbers=str(np.numbers)
string_np_numbers.count('1')

12